version: '3.8'

services:
  migrate:
    image: ${DOCKER_REGISTRY:-myregistry}/social-network:${IMAGE_TAG:-latest}
    command: uv run alembic upgrade head
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.prod
    networks:
      - service_networks

  web:
    image: ${DOCKER_REGISTRY:-myregistry}/social-network:${IMAGE_TAG:-latest}
    ports:
      - "${WEB_PORT:-80}:8000"
    depends_on:
      - migrate
    env_file:
      - .env.prod
    restart: unless-stopped
    networks:
      - service_networks

  db:
    image: postgres:17
    container_name: postgres-master
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./master-config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./master-config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    env_file:
      - .env.prod
    environment:
      - POSTGRES_REPLICATION_USER=replicator
      - POSTGRES_REPLICATION_PASSWORD=replicator_password
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-social_network}"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - service_networks

  db-slave1:
    image: postgres:17
    container_name: postgres-slave1
    ports:
      - "5433:5432"
    volumes:
      - postgres_slave1_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - PGUSER=${POSTGRES_USER:-postgres}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - service_networks

  db-slave2:
    image: postgres:17
    container_name: postgres-slave2
    ports:
      - "5434:5432"
    volumes:
      - postgres_slave2_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - PGUSER=${POSTGRES_USER:-postgres}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - service_networks

volumes:
  postgres_data:
  postgres_slave1_data:
  postgres_slave2_data:


networks:
  service_networks:
    name: service_networks
    driver: bridge
